(define (f this v)
   (let ((fs ($new Array 0)) (l ($get v "length")))
      (let ((i' 0))
	 (let for ()
	    (if ($< i' l)
		(let ((i i'))
		   (($get fs "push") (lambda (_) ($+ i ($get v i))))
		   (set! i ($inc i))
		   (set! i' i)
		   (for)))))
      (($get fs "map") fs (lambda (_ g) (g $undef)))))
